Repository Cykelinspektionen/MjukvaruProjekt, pull requests merged in 2018-11, with the labels that each got.

#21 #10 login support
  .gitignore
  .vscode/launch.json
  Bikeini/.babelrc
  Bikeini/.eslintrc.json
  Bikeini/.flowconfig
  Bikeini/.gitattributes
  Bikeini/.gitignore
  Bikeini/.vscode/launch.json
  Bikeini/.vscode/settings.json
  Bikeini/.watchmanconfig
  Bikeini/App.js
  Bikeini/App.test.js
  Bikeini/__tests__/App-test.js
  Bikeini/app.json
  Bikeini/assets/images/icon.png
  Bikeini/assets/images/splash.png
  Bikeini/babel.config.js
  Bikeini/navigation/AppNavigator.js
  Bikeini/navigation/actions/AuthActions.js
  Bikeini/navigation/actions/types.js
  Bikeini/navigation/reducers/AuthReducers.js
  Bikeini/navigation/reducers/SignUpReducers.js
  Bikeini/navigation/reducers/index.js
  Bikeini/package-lock.json
  Bikeini/package.json
  Bikeini/screens/Login.js
  Bikeini/screens/SignUp.js
  Bikeini/screens/TempPage.js
  Bikeini/utilities/deviceStorage.js
  Bikeini/utilities/serverApi.js
Labels: W45

#27 #17 design and implement location page
  .gitignore
  Bikeini/.eslintrc.json
  Bikeini/.gitignore
  Bikeini/.vscode/settings.json
  Bikeini/assets/Cities.js
  Bikeini/assets/images/biker.png
  Bikeini/navigation/AppNavigator.js
  Bikeini/navigation/actions/ProfileActions.js
  Bikeini/navigation/actions/types.js
  Bikeini/navigation/reducers/AuthReducers.js
  Bikeini/navigation/reducers/ProfileReducers.js
  Bikeini/navigation/reducers/index.js
  Bikeini/package-lock.json
  Bikeini/package.json
  Bikeini/screens/Location.js
  Bikeini/screens/Login.js
  Bikeini/screens/SignUp.js
  Bikeini/utilities/serverApi.js
Labels: W46

#28 #18 bike upload page
  Bikeini/.vscode/settings.json
  Bikeini/assets/images/albumImage.png
  Bikeini/assets/images/camera.png
  Bikeini/assets/images/robot-dev.png
  Bikeini/navigation/AppNavigator.js
  Bikeini/navigation/actions/AddBikeActions.js
  Bikeini/navigation/actions/PermissionActions.js
  Bikeini/navigation/actions/types.js
  Bikeini/navigation/reducers/AddBikeReducers.js
  Bikeini/navigation/reducers/AuthReducers.js
  Bikeini/navigation/reducers/PermissionsReducers.js
  Bikeini/navigation/reducers/index.js
  Bikeini/package-lock.json
  Bikeini/package.json
  Bikeini/screens/AddBike.js
  Bikeini/screens/Camera.js
  Bikeini/screens/Login.js
  Bikeini/screens/SignUp.js
  Bikeini/utilities/permissions.js
Labels: W46

#29 #20 bike browser page
  Bikeini/components/Filter.js
  Bikeini/components/Item.js
  Bikeini/components/ItemCheckbox.js
  Bikeini/navigation/AppNavigator.js
  Bikeini/navigation/actions/FilterActions.js
  Bikeini/navigation/actions/types.js
  Bikeini/navigation/reducers/AuthReducers.js
  Bikeini/navigation/reducers/FilterReducers.js
  Bikeini/navigation/reducers/index.js
  Bikeini/package-lock.json
  Bikeini/screens/Browser.js
  Bikeini/screens/Login.js
  Bikeini/utilities/serverApi.js
  PULL_REQUEST_TEMPLATE.md
Labels: W46

#44 #39 integrate/verify login page
  Bikeini/.vscode/settings.json
  Bikeini/App.js
  Bikeini/navigation/actions/AuthActions.js
  Bikeini/navigation/actions/JwtActions.js
  Bikeini/navigation/actions/ProfileActions.js
  Bikeini/navigation/actions/types.js
  Bikeini/navigation/reducers/AuthReducers.js
  Bikeini/navigation/reducers/ProfileReducers.js
  Bikeini/package-lock.json
  Bikeini/package.json
  Bikeini/screens/Browser.js
  Bikeini/screens/Location.js
  Bikeini/screens/Login.js
  Bikeini/screens/TempPage.js
  Bikeini/utilities/deviceStorage.js
  Bikeini/utilities/serverApi.js
Labels: W47

#52 Fixed location integration with server.
  Bikeini/.vscode/settings.json
  Bikeini/screens/Location.js
  Bikeini/utilities/serverApi.js
Labels: W47

#45 #30 add footer
  Bikeini/assets/Colors.js
  Bikeini/assets/TabBarIcon.js
  Bikeini/navigation/AppNavigator.js
  Bikeini/navigation/BottomNavigator.js
  Bikeini/screens/AddBike.js
  Bikeini/screens/Browser.js
  Bikeini/screens/Login.js
  Bikeini/screens/header.js
Labels: W47

#55 #54Header font now support both iOS and Android
  Bikeini/App.js
  Bikeini/assets/Noteworthy-Bold.ttf
  Bikeini/screens/header.js
Labels: W47, enhancement

#58 #56 profile screen
  Bikeini/navigation/BottomNavigator.js
  Bikeini/screens/Profile.js
Labels: W47

#59 #47 re design bike upload
  Bikeini/navigation/actions/AddBikeActions.js
  Bikeini/navigation/actions/AuthActions.js
  Bikeini/navigation/actions/JwtActions.js
  Bikeini/navigation/actions/ProfileActions.js
  Bikeini/navigation/actions/types.js
  Bikeini/navigation/reducers/AddBikeReducers.js
  Bikeini/navigation/reducers/AuthReducers.js
  Bikeini/navigation/reducers/ProfileReducers.js
  Bikeini/package-lock.json
  Bikeini/screens/AddBike.js
  Bikeini/screens/Browser.js
  Bikeini/screens/Camera.js
  Bikeini/screens/Location.js
  Bikeini/screens/Login.js
  Bikeini/screens/SignUp.js
  Bikeini/utilities/serverApi.js
Labels: W47

#61 Add user info to profile
  Bikeini/screens/Profile.js
Labels: W47, enhancement

#64 #57 bike info screen
  Bikeini/.eslintrc.json
  Bikeini/assets/images/comment.png
  Bikeini/assets/images/location.png
  Bikeini/assets/images/stockBicycle.png
  Bikeini/assets/images/thumbdown.png
  Bikeini/assets/images/thumbup.png
  Bikeini/assets/images/userPlaceholder.jpg
  Bikeini/components/Comment.js
  Bikeini/components/Item.js
  Bikeini/navigation/AppNavigator.js
  Bikeini/package-lock.json
  Bikeini/screens/BikeInformation.js
  Bikeini/screens/Browser.js
Labels: W47

#65 #63 gamification screen
  Bikeini/navigation/BottomNavigator.js
  Bikeini/screens/Gamification.js
  Bikeini/screens/Profile.js
Labels: W48

#67 minor name change, probably source of bug
  Bikeini/screens/AddBike.js
Labels: W48, bug

#69 Minor Bug Fixes (not assigned to an issue)
  Bikeini/screens/BikeInformation.js
  Bikeini/screens/Browser.js
  Bikeini/screens/Profile.js
Labels: bug

#79 #70 game screen
  Bikeini/.vscode/settings.json
  Bikeini/assets/images/FoundBike.png
  Bikeini/components/Comment.js
  Bikeini/package-lock.json
  Bikeini/screens/Gamification.js
  Bikeini/screens/Profile.js
Labels: W48

#82 #75 implement comment buttons
  Bikeini/.vscode/settings.json
  Bikeini/assets/images/thumbdownNoBack.png
  Bikeini/assets/images/thumbupNoBack.png
  Bikeini/components/Comment.js
  Bikeini/components/Item.js
  Bikeini/screens/BikeInformation.js
  Bikeini/screens/Browser.js
  Bikeini/screens/Profile.js
Labels: W48

#89 #48 verify browser page
  Bikeini/screens/BikeInformation.js
  Bikeini/screens/Browser.js
  Bikeini/screens/Profile.js
Labels: W47

#91 Added local top list
  Bikeini/screens/Gamification.js
  Bikeini/screens/Profile.js
Labels: W48

#87 #84 fix comment button <item>
  Bikeini/components/Item.js
  Bikeini/screens/Browser.js
  Bikeini/screens/Profile.js
Labels: W48

#99 Changed Gamification screen based on DB changes
  Bikeini/screens/Browser.js
  Bikeini/screens/Gamification.js
  Bikeini/screens/Login.js
  Bikeini/screens/Profile.js
Labels: W48

#102 #72 implement pointsystem
  Bikeini/components/Comment.js
  Bikeini/components/Item.js
  Bikeini/navigation/reducers/ProfileReducers.js
  Bikeini/screens/BikeInformation.js
  Bikeini/screens/Browser.js
  Bikeini/screens/Gamification.js
  Bikeini/screens/Location.js
  Bikeini/screens/Login.js
  Bikeini/screens/Profile.js
  Bikeini/screens/SignUp.js
Labels: W48
