Repository Cykelinspektionen/MjukvaruProjekt, pull requests merged in 2018-12, with the labels that each got.

#111 #100 css fix
  Bikeini/assets/images/background.jpeg
  Bikeini/screens/AddBike.js
  Bikeini/screens/Browser.js
  Bikeini/screens/Gamification.js
  Bikeini/screens/Profile.js
Labels: W49

#112 #96 integrate ml response with client
  Bikeini/screens/AddBike.js
Labels: W48

#144 #117 Implements search functionality for cities.
  Bikeini/screens/Location.js
Labels: W49

#142 #116 min password
  Bikeini/screens/AddBike.js
  Bikeini/screens/SignUp.js
Labels: W49

#146 Logout button on profile page
  Bikeini/navigation/actions/ProfileActions.js
  Bikeini/navigation/actions/types.js
  Bikeini/navigation/reducers/ProfileReducers.js
  Bikeini/screens/Login.js
  Bikeini/screens/Profile.js
Labels: W49

#145 Added bikes you have submitted tips about on profile screen
  Bikeini/App.js
  Bikeini/assets/fonts/Noteworthy-Bold.ttf
  Bikeini/package.json
  Bikeini/screens/Profile.js
  Bikeini/screens/header.js
Labels: W49

#155 #72 implement pointsystem
  Bikeini/components/Comment.js
  Bikeini/navigation/reducers/AuthReducers.js
  Bikeini/navigation/reducers/ProfileReducers.js
  Bikeini/screens/BikeInformation.js
  Bikeini/screens/Browser.js
  Bikeini/screens/Profile.js
  Bikeini/utilities/Const.js
Labels: W48, W49

#156 fixed lat and long in add bike, changed to addbike enpoint
  Bikeini/navigation/actions/AddBikeActions.js
  Bikeini/screens/AddBike.js
Labels: W49, bug

#158 minor css fix for proifle
  Bikeini/screens/Profile.js
Labels: W48, enhancement

#153 Gamification screen can now be updated
  Bikeini/navigation/actions/AuthActions.js
  Bikeini/navigation/actions/types.js
  Bikeini/navigation/reducers/AuthReducers.js
  Bikeini/screens/Gamification.js
  Bikeini/screens/Location.js
  Bikeini/screens/Login.js
Labels: W49

#163 Change what information is displayed in the addlist, also changed bik…
  Bikeini/components/Comment.js
  Bikeini/components/Item.js
  Bikeini/screens/BikeInformation.js
  Bikeini/screens/Browser.js
  Bikeini/screens/Profile.js
Labels: W49

#160 fixed points in comments and thumbs
  Bikeini/components/Comment.js
Labels: W49, W50

#164 #136 filter function
  Bikeini/components/Filter.js
  Bikeini/components/ItemCheckbox.js
  Bikeini/navigation/actions/FilterActions.js
  Bikeini/navigation/actions/types.js
  Bikeini/navigation/reducers/FilterReducers.js
  Bikeini/package-lock.json
  Bikeini/package.json
  Bikeini/screens/Browser.js
Labels: W49

#166 #130 forgot password
  Bikeini/navigation/AppNavigator.js
  Bikeini/navigation/actions/ResetPasswordActions.js
  Bikeini/navigation/actions/types.js
  Bikeini/navigation/reducers/ResetPasswordReducers.js
  Bikeini/navigation/reducers/index.js
  Bikeini/screens/Login.js
  Bikeini/screens/ResetPassword.js
  Bikeini/utilities/serverApi.js
Labels: W49

#169 #123 add profile picture
  Bikeini/components/Comment.js
  Bikeini/navigation/actions/ProfileActions.js
  Bikeini/navigation/actions/types.js
  Bikeini/navigation/reducers/ProfileReducers.js
  Bikeini/screens/BikeInformation.js
  Bikeini/screens/Gamification.js
  Bikeini/screens/Profile.js
Labels: W49, W50

#174 thumbnail fix
  Bikeini/screens/BikeInformation.js
  Bikeini/screens/Browser.js
  Bikeini/screens/Profile.js
Labels: W50, bug

#173 Header for BikeInformation + More header related changes/additions
  Bikeini/navigation/AppNavigator.js
  Bikeini/navigation/BottomNavigator.js
  Bikeini/navigation/actions/MapActions.js
  Bikeini/navigation/actions/types.js
  Bikeini/package-lock.json
  Bikeini/screens/AddBike.js
  Bikeini/screens/BikeInformation.js
  Bikeini/screens/Browser.js
  Bikeini/screens/Camera.js
  Bikeini/screens/Gamification.js
  Bikeini/screens/Location.js
  Bikeini/screens/Login.js
  Bikeini/screens/PinMap.js
  Bikeini/screens/Profile.js
  Bikeini/screens/ResetPassword.js
  Bikeini/screens/SignUp.js
  Bikeini/screens/header.js
Labels: W50

#177 #109 add bike location
  Bikeini/navigation/actions/AddBikeActions.js
  Bikeini/navigation/reducers/MapReducers.js
  Bikeini/screens/AddBike.js
  Bikeini/screens/Camera.js
  Bikeini/screens/PinMap.js
Labels: W50

#180 #128 edit own comment
  Bikeini/components/Comment.js
  Bikeini/package-lock.json
  Bikeini/package.json
  Bikeini/screens/BikeInformation.js
  Bikeini/screens/Browser.js
  Bikeini/screens/Gamification.js
  Bikeini/screens/Location.js
  Bikeini/screens/SignUp.js
  Bikeini/utilities/serverApi.js
  README.md
Labels: W50

#186 Fixes thumbs in users own comment
  Bikeini/components/Comment.js
Labels: W50

#185 #178 add location bike info
  Bikeini/.vscode/launch.json
  Bikeini/components/Comment.js
  Bikeini/components/Item.js
  Bikeini/package-lock.json
  Bikeini/package.json
  Bikeini/screens/BikeInformation.js
  Bikeini/screens/Browser.js
  Bikeini/screens/Profile.js
Labels: W50

#192 #124 comments counter
  Bikeini/assets/images/emptyComment.png
  Bikeini/components/Item.js
  Bikeini/screens/BikeInformation.js
  Bikeini/screens/Browser.js
  Bikeini/screens/Profile.js
Labels: W50

#191 #133 change add bike radio buttons
  Bikeini/navigation/actions/AddBikeActions.js
  Bikeini/navigation/actions/ProfileActions.js
  Bikeini/navigation/actions/types.js
  Bikeini/navigation/reducers/ProfileReducers.js
  Bikeini/package-lock.json
  Bikeini/package.json
  Bikeini/screens/AddBike.js
  Bikeini/utilities/serverApi.js
Labels: W50

#182 Fixed gamification screen to work on Android phones to. Also fixed pr…
  Bikeini/navigation/reducers/ProfileReducers.js
  Bikeini/screens/BikeInformation.js
  Bikeini/screens/Gamification.js
  Bikeini/screens/Profile.js
Labels: W50

#193 disabled ios swipe on some screens
  Bikeini/components/Comment.js
  Bikeini/components/Item.js
  Bikeini/navigation/AppNavigator.js
  Bikeini/screens/Gamification.js
  Bikeini/screens/Profile.js
Labels: bug

#197 #120 answer button
  Bikeini/components/Comment.js
  Bikeini/navigation/AppNavigator.js
  Bikeini/navigation/BottomNavigator.js
  Bikeini/screens/AddBike.js
  Bikeini/screens/BikeInformation.js
  Bikeini/screens/Browser.js
  Bikeini/screens/Gamification.js
  Bikeini/screens/Profile.js
  Bikeini/screens/header.js
Labels: W50

#198 Fixed icon bug with a "hack"
  Bikeini/package-lock.json
  Bikeini/screens/PinMap.js
Labels: W50, bug

#202 #118 profile notification
  Bikeini/App.js
  Bikeini/App.test.js
  Bikeini/__tests__/App-test.js
  Bikeini/babel.config.js
  Bikeini/components/FooterIcon.js
  Bikeini/navigation/BottomNavigator.js
  Bikeini/navigation/actions/ProfileActions.js
  Bikeini/navigation/actions/RouteActions.js
  Bikeini/navigation/actions/types.js
  Bikeini/navigation/reducers/ProfileReducers.js
  Bikeini/navigation/reducers/RouteReducers.js
  Bikeini/navigation/reducers/index.js
  Bikeini/package-lock.json
  Bikeini/screens/Gamification.js
  Bikeini/screens/PinMap.js
  Bikeini/screens/Profile.js
Labels: W50

#200 #132 css verification and cleanup
  Bikeini/assets/images/album.png
  Bikeini/assets/images/bikePlaceholder.png
  Bikeini/components/Comment.js
  Bikeini/components/Filter.js
  Bikeini/components/Item.js
  Bikeini/screens/AddBike.js
  Bikeini/screens/Browser.js
  Bikeini/screens/Gamification.js
  Bikeini/screens/Login.js
  Bikeini/screens/Profile.js
  Bikeini/screens/ResetPassword.js
  Bikeini/screens/SignUp.js
Labels: W50

#207 #161 refactor icon loadin
  Bikeini/App.js
  Bikeini/assets/images/FoundBike.png
  Bikeini/assets/images/Not used/background (kopia).jpeg
  Bikeini/assets/images/Not used/robot-dev.png
  Bikeini/assets/images/Not used/thumbdown.png
  Bikeini/assets/images/Not used/thumbup.png
  Bikeini/assets/images/album.png
  Bikeini/assets/images/background.jpeg
  Bikeini/assets/images/biker.png
  Bikeini/assets/images/comment.jpeg
  Bikeini/assets/images/comment.png
  Bikeini/assets/images/emptyComment.png
  Bikeini/assets/images/location.png
  Bikeini/assets/images/thumbdownNoBack.png
  Bikeini/assets/images/thumbupNoBack.png
  Bikeini/assets/images/userPlaceholder.jpg
  Bikeini/screens/Profile.js
Labels: W51

#214 #126 matching counter
  Bikeini/components/Item.js
  Bikeini/screens/AddBike.js
  Bikeini/screens/BikeInformation.js
  Bikeini/screens/Browser.js
  Bikeini/screens/Profile.js
Labels: W51

#213 #209 force profile 4 3
  Bikeini/screens/AddBike.js
  Bikeini/screens/Profile.js
Labels: W51

#219 #216 addbike loc bug
  Bikeini/screens/AddBike.js
  Bikeini/screens/PinMap.js
Labels: W51, bug

#217 #132 css verification and cleanup
  Bikeini/App.js
  Bikeini/assets/images/albumImage.png
  Bikeini/assets/images/emptyComment.png
  Bikeini/components/Comment.js
  Bikeini/components/Item.js
  Bikeini/package-lock.json
  Bikeini/package.json
  Bikeini/screens/AddBike.js
  Bikeini/screens/BikeInformation.js
  Bikeini/screens/Browser.js
  Bikeini/screens/Login.js
  Bikeini/screens/PinMap.js
  Bikeini/screens/ResetPassword.js
  Bikeini/screens/SignUp.js
Labels: W51

#237 Back button in header nav. in Pinmap is now removed
  Bikeini/navigation/AppNavigator.js
Labels: bug

#239 #210 integrate new server
  Bikeini/components/Filter.js
  Bikeini/components/FooterIcon.js
  Bikeini/navigation/actions/ProfileActions.js
  Bikeini/navigation/reducers/ProfileReducers.js
  Bikeini/screens/AddBike.js
  Bikeini/screens/Gamification.js
  Bikeini/screens/Profile.js
  Bikeini/utilities/serverApi.js
Labels: W51

#242 #231 reset all states
  Bikeini/navigation/actions/AuthActions.js
  Bikeini/navigation/actions/RootActions.js
  Bikeini/navigation/actions/types.js
  Bikeini/navigation/reducers/index.js
  Bikeini/screens/EditProfile.js
  Bikeini/screens/Profile.js
Labels: bug

#241 Requires Title, Model and Description
  Bikeini/screens/AddBike.js
Labels: W51

#238 Sends now email when uploading profile pic instead of username
  Bikeini/screens/Profile.js
Labels: W51, bug
