Repository Cykelinspektionen/MjukvaruProjekt, pull requests merged in 2019-01, with the labels that each got.

#249 More integration work with client and new back-end.
  Bikeini/screens/AddBike.js
Labels: W51, bug

#248 Design fixes
  Bikeini/components/Filter.js
  Bikeini/screens/AddBike.js
  Bikeini/screens/Browser.js
  Bikeini/screens/EditProfile.js
  Bikeini/screens/Profile.js
Labels: W02

#252 Small fixes in Addbike.js
  Bikeini/navigation/reducers/AddBikeReducers.js
  Bikeini/screens/AddBike.js
Labels: bug

#254 fixed overlap with hotfix
  Bikeini/screens/BikeInformation.js
Labels: bug

#255 Changed font size in bikeinfo
  Bikeini/screens/BikeInformation.js
Labels: bug
